### ISSUE TITLE
century year handling

### ISSUE THREAD

**Issue by nickolas1** [anveshkolluri93/validate-date#4]
Hi there,

the handling of century years seems to be not quite correct- they should only be leap years if they are divisible by 400, so 1900 and 2100 are not leap years, while 2000 is. I believe this could be fixed with a change like this to `daysInMonth`:

`return (month === 2 && year % 4 === 0 && (year % 100 === 0 ? year % 400 === 0 : true)) ? 29 : days[month - 1];`

**Comment by anveshkolluri93** [comment]
please, feel free to open a PR for this if you want to contribute. I will be a bit late to given my current timeline. thanks

**Comment by anveshkolluri93** [comment]
#10 This issue has been addressed. Please, use the updated version of the package to get the updates.
